const fs = require("fs");
const path = require("path");

const content = [
  "import React from 'react';",
  "import { Dimensions, Pressable, StyleSheet, Text, View } from 'react-native';",
  "import { LinearGradient } from 'expo-linear-gradient';",
  "",
  "const { width } = Dimensions.get('window');",
  "const CARD_WIDTH = (width - 20 * 2 - 10 * 2) / 3;",
  "",
  "type GradientTuple = [string, string];",
  "type GradientTriple = [string, string, string];",
  "",
  "const CARDS: {",
  "  id: string;",
  "  label: string;",
  "  description: string;",
  "  gradient: GradientTuple;",
  "  illustrationGradient: GradientTuple;",
  "  borderGradient: GradientTriple;",
  "  arrowBg: string;",
  "  illustrationEmoji: string;",
  "}[] = [",
  "  {",
  "    id: 'draw',",
  "    label: 'DRAW YOUR\\nHERO',",
  '    description: "I\'ll turn your drawing into a real character!",',
  "    gradient: ['#1E4ED8', '#1E3A8A'],",
  "    illustrationGradient: ['#3B82F6', '#1D4ED8'],",
  "    borderGradient: ['#60A5FA', '#3B82F6', '#1E3A8A'],",
  "    arrowBg: '#2563EB',",
  "    illustrationEmoji: '\\u{1F409}',",
  "  },",
  "  {",
  "    id: 'random',",
  "    label: 'RANDOM\\nADVENTURE',",
  "    description: 'Surprise me with a cool story!',",
  "    gradient: ['#7C3AED', '#4C1D95'],",
  "    illustrationGradient: ['#8B5CF6', '#6D28D9'],",
  "    borderGradient: ['#A78BFA', '#7C3AED', '#4C1D95'],",
  "    arrowBg: '#6D28D9',",
  "    illustrationEmoji: '\\u{1F680}',",
  "  },",
  "  {",
  "    id: 'stories',",
  "    label: 'MY\\nSTORIES',",
  "    description: 'Go back & play again!',",
  "    gradient: ['#0D9488', '#065F46'],",
  "    illustrationGradient: ['#14B8A6', '#0F766E'],",
  "    borderGradient: ['#2DD4BF', '#0D9488', '#065F46'],",
  "    arrowBg: '#0F766E',",
  "    illustrationEmoji: '\\u{1F4D6}',",
  "  },",
  "];",
  "",
  "export default function MagicStartSection() {",
  "  return (",
  "    <View style={styles.container}>",
  "      <View style={styles.headerRow}>",
  "        <Text style={styles.starIcon}>\\u2B50</Text>",
  "        <Text style={styles.headerText}> Pick a Magic Start </Text>",
  "        <Text style={styles.wavyText}>\\u301C</Text>",
  "      </View>",
  "      <View style={styles.cardsRow}>",
  "        {CARDS.map((card) => (",
  "          <Pressable key={card.id} style={styles.cardOuter}>",
  "            <LinearGradient",
  "              colors={card.borderGradient}",
  "              start={{ x: 0, y: 0 }}",
  "              end={{ x: 1, y: 1 }}",
  "              style={styles.cardBorderGradient}",
  "            >",
  "              <LinearGradient",
  "                colors={card.gradient}",
  "                start={{ x: 0, y: 0 }}",
  "                end={{ x: 0, y: 1 }}",
  "                style={styles.card}",
  "              >",
  "                <LinearGradient",
  "                  colors={card.illustrationGradient}",
  "                  start={{ x: 0, y: 0 }}",
  "                  end={{ x: 1, y: 1 }}",
  "                  style={styles.illustration}",
  "                >",
  "                  <View style={styles.glowCircle} />",
  "                  <Text style={styles.illustrationEmoji}>{card.illustrationEmoji}</Text>",
  "                </LinearGradient>",
  "                <Text style={styles.cardLabel}>{card.label}</Text>",
  "                <Text style={styles.cardDescription}>{card.description}</Text>",
  "                <View style={[styles.arrowBtn, { backgroundColor: card.arrowBg }]}>",
  "                  <Text style={styles.arrowText}>{'>'}  </Text>",
  "                </View>",
  "              </LinearGradient>",
  "            </LinearGradient>",
  "          </Pressable>",
  "        ))}",
  "      </View>",
  "    </View>",
  "  );",
  "}",
  "",
  "const styles = StyleSheet.create({",
  "  container: { paddingHorizontal: 20, paddingTop: 24, paddingBottom: 16 },",
  "  headerRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 16 },",
  "  starIcon: { fontSize: 20 },",
  "  headerText: { fontFamily: 'Montserrat_800ExtraBold', fontSize: 16, color: '#FFFFFF' },",
  "  wavyText: { fontSize: 18, color: '#C084FC' },",
  "  cardsRow: { flexDirection: 'row', gap: 10 },",
  "  cardOuter: { width: CARD_WIDTH, borderRadius: 20, overflow: 'hidden' },",
  "  cardBorderGradient: { borderRadius: 20, padding: 1.5 },",
  "  card: { borderRadius: 18, padding: 10, minHeight: 210, overflow: 'hidden', justifyContent: 'flex-end' },",
  "  illustration: { position: 'absolute', top: 0, left: 0, right: 0, height: 110, borderRadius: 14, alignItems: 'center', justifyContent: 'center', overflow: 'hidden' },",
  "  glowCircle: { position: 'absolute', width: 70, height: 70, borderRadius: 35, backgroundColor: 'rgba(255,255,255,0.15)' },",
  "  illustrationEmoji: { fontSize: 44 },",
  "  cardLabel: { fontFamily: 'Montserrat_800ExtraBold', fontSize: 12, color: '#FFFFFF', marginTop: 118, marginBottom: 4, lineHeight: 15 },",
  "  cardDescription: { fontSize: 10, color: 'rgba(255,255,255,0.75)', lineHeight: 13, marginBottom: 10 },",
  "  arrowBtn: { width: 28, height: 28, borderRadius: 14, alignItems: 'center', justifyContent: 'center', alignSelf: 'flex-end' },",
  "  arrowText: { color: '#FFFFFF', fontSize: 20, lineHeight: 22, fontWeight: '700' },",
  "});",
].join("\n");

fs.writeFileSync(
  path.join(__dirname, "../components/MagicStartSection.tsx"),
  content,
);
console.log("Written successfully");
